### PR TITLE
popup: Backported frontend fixes from Chrome

### PR DESCRIPTION
**Pull request by mrshu**
* Backported frontend fixes from the Chrome extension's popup
  (https://github.com/duckduckgo/chrome-zeroclickinfo/pull/18)

Signed-off-by: mr.Shu <mr@shu.io>

### CODE REVIEW

**Comment by mrshu** [comment]
@bbraithwaite @thm I tried to backport @bbraithwaite's fixes to the safari extension too and it looks pretty good (see the attached image)!

Would you mind trying to install it from here: https://github.com/duckduckgo/safari-zeroclickinfo/blob/mrshu/frontend-fixes/build/duckduckgo.safariextz?raw=true and pointing out anything that might be wrong?

Thanks a ton!

safari

**Comment by thm** [comment]
@mrshu @bbraithwaite Nice!:
1. the extension seems to be clipped off for me. Restarting Safari (v9.0.3 11601.4.4) doesn't fix it. 
2. in your screenshot I notice the bottom padding is a bit much, maybe it's related?
screen shot 2016-02-10 at 5 45 54 pm

**Comment by mrshu** [comment]
@thm hmm, yes, this seems related.

Will take a closer look and let you know.

**Comment by mrshu** [comment]
@thm Thanks again for the ping, I believe I found the culprit.

Can you please install it once again from this link (for real this time =) ): https://github.com/duckduckgo/safari-zeroclickinfo/blob/mrshu/frontend-fixes/build/duckduckgo.safariextz?raw=true ?

Thanks!

**Comment by thm** [comment]
@mrshu that did the trick, LGTM!

**Comment by mrshu** [comment]
Thanks @thm!

**Pull request merged**
